name: Terraform CI CD Pipeline for Deploying AWS Resources
run-name: ${{ github.actor }} has triggered the pipeline
on:
  workflow_dispatch:
    inputs:
      terraform_plan:
        type: choice
        description: select terraform action
        options:
        - ok 
        - not 
        required: true
      terraform_action:
        type: choice
        description: select terraform action
        options:
        - apply
        - destroy
        required: true
  
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-infra:
    name: terraform-ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./Terraform-VPC
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./Terraform-VPC
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./Terraform-VPC
      - name: Terraform Apply
        id: apply
        if: ${{ github.event.inputs.terraform_action == 'apply' && github.event.inputs.terraform_plan == 'ok'}}
        run: terraform ${{ github.event.inputs.terraform_action }}
        working-directory: ./Terraform-VPC
      - name: Terraform Apply
        id: destroy
        if: ${{ github.event.inputs.terraform_action == 'destroy' && github.event.inputs.terraform_plan == 'ok' }}
        run: terraform ${{ github.event.inputs.terraform_action }}
        working-directory: ./Terraform-VPC

